
---
apiVersion: v1
kind: Service
metadata:
  # name: dov-svc
  name: dov-hsvc
  namespace: dovns
  labels:
    app: dov
    name: dov-svc
spec:
  # type: ClusterIP
  clusterIP: None
  selector:
    app: dov
    name: dov-po
  ports:
  - port: 3000 # service port
    targetPort: 3000

---

apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: dov-sts
  namespace: dovns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dov
  serviceName: dov-hsvc
  template:
    metadata:
      labels:
        app: dov
    spec:
      containers:
      - name: dov-sts
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
