---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage  # get name by 'k get sc'
---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-po
  namespace: default
spec: 
  volumes:
  - name: data-vol
    persistentVolumeClaim: 
      claimName: mysql-pvc
  containers: 
    - name : mysql-container
      image: mysql:8
      env: 
      - name: MYSQL_ROOT_PASSWORD
        value: changit
      ports: 
      - containerPort: 3306
      volumeMounts: 
      - name: data-vol #
        mountPath: /var/lib/mysql
      resources: {}

  # k apply -f mysql-pv.yaml
  # k get pvc,pv
  # k describe pvc/mysql-pvc
