volumes: 
# docker volume create data-vol
  data-vol: 

networks:
# docker network create mynet 
  mynet:

services:
  # docker run -d --name=mydb --network=mynet --mount type=volume, src=data-vol, dst=/var/lib/mysql \
  # chukmunnlee/mydb:v1
  mydb:
    image: chukmunnlee/mydb:v1 
    build:
      context: database
    volumes: 
    - data-vol:/var/lib/mysql
    networoks:
    - mynet

  # docker run -d -p 8000-9000:3000 --network=mynet -e DB_host=mydb -e DB_USER=root -e DB_PASSWORD=changeit\ chukmunnlee/myapp:v1
  myapp:
    image: chukmunnlee/myapp:v1
    build:
      context:server
    environment:
    - DB_HOST= mydb
    - DB_USER=root
    - DB_PASSWORD=changit

    networks:
    - mynet 
    ports:
    - 8000-9000:3000
    depends_on:
    - mydb


# # command to build both images:
# docker compose build