---
apiVersion: v1
kind: Namespace
metadata: 
  name: myns
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: myns 
  labels:
    app: myapp
    dept: eng 
    commit: abc123
spec: 
  containers:
  - name: mypod-container
    image: chukmunnlee/dov-bear@sha256:483038792aba29562a4d2044e790d7d3e7e6e6f684ce1fcafc3864949c000224 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
    env:
    - name: INSTANCE_NAME
      value: my first pod 
    - name: INSTANCE_HASH
      value: abc123


